# Generated by Django 4.1.4 on 2022-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkswagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='mail',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='numbers',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
