# Generated by Django 4.1.3 on 2022-12-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkswagen', '0002_alter_footer_address_alter_footer_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='numbers',
        ),
        migrations.AddField(
            model_name='footer',
            name='number_phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='mail',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
