# Generated by Django 4.1.3 on 2022-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length='50', null=True, upload_to='')),
                ('description', models.TextField(max_length='50', null=True)),
            ],
        ),
    ]
