# Generated by Django 4.1.1 on 2022-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_catal'),
    ]

    operations = [
        migrations.AddField(
            model_name='catal',
            name='carType',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Sedan'), (2, 'Hatchback'), (3, 'Universal'), (4, 'SUV'), (5, 'Truck'), (6, 'Minivan'), (7, 'Coupe'), (8, 'Roadster')], default=0),
        ),
        migrations.AddField(
            model_name='catal',
            name='isNew',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catal',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catal',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catal',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catal',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
