# Generated by Django 4.1.1 on 2022-11-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_catal_cartype_catal_isnew_catal_name_catal_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catal',
            name='isNew',
        ),
    ]
