# Generated by Django 4.1.3 on 2022-12-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_commenttvshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentTvShow',
            new_name='Comment',
        ),
    ]
