# Generated by Django 4.1.3 on 2022-12-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_commenttvshow_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentCar',
        ),
    ]
